config:
  gcp:project: ryan953-lifting-prod
  gcp:region: us-central1
  lifting:firestoreLocation: nam5
  lifting:githubRepository: ryan953/lifting
  lifting:githubBranch: main
  lifting:hostingSiteId: ryan953-lifting-v3
  lifting:emailPasswordAuth: "true"
  # lifting:extraAuthDomains: '["lifting.ryan953.com"]'
