/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppExercisesRouteImport } from './routes/_app/exercises'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppExercisesIndexRouteImport } from './routes/_app/exercises.index'
import { Route as AppExercisesExerciseIdRouteImport } from './routes/_app/exercises.$exerciseId'
import { Route as AppExercisesNewRouteImport } from './routes/_app/exercises.new'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesIndexRoute = AppExercisesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppExercisesRoute,
} as any)
const AppExercisesExerciseIdRoute = AppExercisesExerciseIdRouteImport.update({
  id: '/$exerciseId',
  path: '/$exerciseId',
  getParentRoute: () => AppExercisesRoute,
} as any)
const AppExercisesNewRoute = AppExercisesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppExercisesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/exercises': typeof AppExercisesRouteWithChildren
  '/history': typeof AppHistoryRoute
  '/templates': typeof AppTemplatesRoute
  '/exercises/$exerciseId': typeof AppExercisesExerciseIdRoute
  '/exercises/new': typeof AppExercisesNewRoute
  '/exercises/': typeof AppExercisesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/history': typeof AppHistoryRoute
  '/templates': typeof AppTemplatesRoute
  '/': typeof AppIndexRoute
  '/exercises/$exerciseId': typeof AppExercisesExerciseIdRoute
  '/exercises/new': typeof AppExercisesNewRoute
  '/exercises': typeof AppExercisesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/exercises': typeof AppExercisesRouteWithChildren
  '/_app/history': typeof AppHistoryRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/exercises/$exerciseId': typeof AppExercisesExerciseIdRoute
  '/_app/exercises/new': typeof AppExercisesNewRoute
  '/_app/exercises/': typeof AppExercisesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/exercises'
    | '/history'
    | '/templates'
    | '/exercises/$exerciseId'
    | '/exercises/new'
    | '/exercises/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/history'
    | '/templates'
    | '/'
    | '/exercises/$exerciseId'
    | '/exercises/new'
    | '/exercises'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/exercises'
    | '/_app/history'
    | '/_app/templates'
    | '/_app/'
    | '/_app/exercises/$exerciseId'
    | '/_app/exercises/new'
    | '/_app/exercises/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises': {
      id: '/_app/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises/': {
      id: '/_app/exercises/'
      path: '/'
      fullPath: '/exercises/'
      preLoaderRoute: typeof AppExercisesIndexRouteImport
      parentRoute: typeof AppExercisesRoute
    }
    '/_app/exercises/$exerciseId': {
      id: '/_app/exercises/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof AppExercisesExerciseIdRouteImport
      parentRoute: typeof AppExercisesRoute
    }
    '/_app/exercises/new': {
      id: '/_app/exercises/new'
      path: '/new'
      fullPath: '/exercises/new'
      preLoaderRoute: typeof AppExercisesNewRouteImport
      parentRoute: typeof AppExercisesRoute
    }
  }
}

interface AppExercisesRouteChildren {
  AppExercisesExerciseIdRoute: typeof AppExercisesExerciseIdRoute
  AppExercisesNewRoute: typeof AppExercisesNewRoute
  AppExercisesIndexRoute: typeof AppExercisesIndexRoute
}

const AppExercisesRouteChildren: AppExercisesRouteChildren = {
  AppExercisesExerciseIdRoute: AppExercisesExerciseIdRoute,
  AppExercisesNewRoute: AppExercisesNewRoute,
  AppExercisesIndexRoute: AppExercisesIndexRoute,
}

const AppExercisesRouteWithChildren = AppExercisesRoute._addFileChildren(
  AppExercisesRouteChildren,
)

interface AppRouteChildren {
  AppExercisesRoute: typeof AppExercisesRouteWithChildren
  AppHistoryRoute: typeof AppHistoryRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExercisesRoute: AppExercisesRouteWithChildren,
  AppHistoryRoute: AppHistoryRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
